class Test{
	public static void main(String []args){
	SinglyLinkedList ob1=new SinglyLinkedList();
	ob1.insert_at_head(0);
	ob1.insert_at_head(10);
	ob1.insert_at_head(20);
	ob1.insert_at_head(30);
	ob1.insert_at_head(40);
	ob1.insert_at_head(50);
	ob1.print();
	System.out.println();
	SinglyLinkedList ob2=new SinglyLinkedList();
	ob2.insert_at_tail(0);
	ob2.insert_at_tail(10);
	ob2.insert_at_tail(20);
	ob2.insert_at_tail(30);
	ob2.insert_at_tail(40);
	ob2.insert_at_tail(50);
	ob2.print();
	System.out.println();
	ob2.insert_at_position(60,3);
	ob2.print();
	System.out.println();
	ob2.delete_at_pos(1);
	ob2.print();
	System.out.println();
	ob2.delete_at_value(60);
	ob2.print();
	System.out.println();
	ob2. no_of_nodes();
	System.out.println("sum is "+ob2.sum());
	ob2.changenode(20,100);
	ob2.print();
	System.out.println();
	ob2.print();
	ob2.move_large_end();
	ob2.print();
	System.out.println();
	ob2.search(100);
	ob1.print();
	System.out.println();
	ob2.print();
	ob2.concatenate(ob1);
	ob1.print();
	System.out.println();
	SinglyLinkedList ob3=new SinglyLinkedList();
	ob3.insert_at_tail(10);
	ob3.insert_at_tail(20);
	ob3.insert_at_tail(30);
	ob3.insert_at_tail(40);
	ob3.insert_at_tail(50);
	ob3.insert_at_tail(60);
	ob3.insert_at_tail(70);
	ob3.insert_at_tail(80);
	ob3.insert_at_tail(90);
	ob3.insert_at_tail(100);
	ob3.print();
	System.out.println();
	ob3.delete_even();
	ob3.print();
	SinglyLinkedList ob4=new SinglyLinkedList();
	ob4.insert_at_tail(10);
	ob4.insert_at_tail(20);
	ob4.insert_at_tail(30);
	ob4.insert_at_tail(40);
	ob4.insert_at_tail(50);
	ob4.insert_at_tail(60);
	ob4.insert_at_tail(70);
	ob4.insert_at_tail(80);
	ob4.insert_at_tail(90);
	ob4.insert_at_tail(100);
	ob4.print();
	System.out.println();
	ob4.split();
	System.out.println();
	System.out.print("the elements in odd position are:  ");
	ob4.print();
	System.out.println();
	SinglyLinkedList ob5=new SinglyLinkedList();
	ob5.insert_at_tail(10);
	ob5.insert_at_tail(20);
	ob5.insert_at_tail(30);
	ob5.insert_at_tail(40);
	ob5.insert_at_tail(50);
	ob5.insert_at_tail(60);
	ob5.insert_at_tail(70);
	ob5.insert_at_tail(80);
	ob5.insert_at_tail(90);
	ob5.insert_at_tail(100);
	ob5.print();
	System.out.println();
	ob5.reversewithrecursion(ob5.head,0);
	System.out.println("the reversed linked list is:  ");
	ob5.print();
	}
}


